<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dl7eouhxf/image/upload/v1554403608/chris.jpg" alt="Mark Essien">
                        <h6>Akinloye Omotomiwa</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://linkedin.com/in/omotomiwa-christopher-626984134" target="_blank"<i class="fab fa-linkedin"></i></a></li>
                           <li><a href="https://github.com/omotomiwa" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@tomchris769" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am Omotomiwa, a technology enthusiast, i am a JavaScript front end engineer</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | React</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
